[build]
  functions = "netlify/functions"
  publish   = "."

# Regra específica para o endpoint do iFood
[[redirects]]
  from    = "/webhook"
  to      = "/.netlify/functions/ifood-webhook"
  status  = 200
  force   = true
  methods = ["GET","POST","OPTIONS"]

# Regra para o endpoint interno de eventos
[[redirects]]
  from    = "/webhook-events"
  to      = "/.netlify/functions/ifood-webhook-events"
  status  = 200
  force   = true
  methods = ["GET","POST","OPTIONS"]

# Catch‑all para SPA/client‑side routing
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
