[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/ifood-webhook"
  status = 200
  force = true
  methods = ["GET","POST","OPTIONS"]
``` :contentReference[oaicite:6]{index=6}.

[[redirects]]
  from = "/webhook-events"
  to = "/.netlify/functions/ifood-webhook-events"
  status = 200
  force = true
